//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YpiControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YpiControl.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string ATTR_ALIAS {
            get {
                return ResourceManager.GetString("ATTR_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BubbleId.
        /// </summary>
        internal static string ATTR_BUBBLE_ID {
            get {
                return ResourceManager.GetString("ATTR_BUBBLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to npc_{0}.
        /// </summary>
        internal static string ATTR_BUBBLE_ID_DEFAULT {
            get {
                return ResourceManager.GetString("ATTR_BUBBLE_ID_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chapterUrl.
        /// </summary>
        internal static string ATTR_CHAPTER_URL {
            get {
                return ResourceManager.GetString("ATTR_CHAPTER_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdleInterval.
        /// </summary>
        internal static string ATTR_IDLE_INTERVAL {
            get {
                return ResourceManager.GetString("ATTR_IDLE_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initState.
        /// </summary>
        internal static string ATTR_INIT_STATE {
            get {
                return ResourceManager.GetString("ATTR_INIT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isAutostart.
        /// </summary>
        internal static string ATTR_IS_AUTOSTART {
            get {
                return ResourceManager.GetString("ATTR_IS_AUTOSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isSoundEnabled.
        /// </summary>
        internal static string ATTR_IS_SOUND_ENABLED {
            get {
                return ResourceManager.GetString("ATTR_IS_SOUND_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ATTR_NAME {
            get {
                return ResourceManager.GetString("ATTR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string ATTR_SPEED {
            get {
                return ResourceManager.GetString("ATTR_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string DELIM_COMMA {
            get {
                return ResourceManager.GetString("DELIM_COMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number format!.
        /// </summary>
        internal static string ERROR_INVALID_NUMBER_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_INVALID_NUMBER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;{0}&quot;/&gt;.
        /// </summary>
        internal static string INCLUDE_STYLESHEET_URL {
            get {
                return ResourceManager.GetString("INCLUDE_STYLESHEET_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YpiControl.jquery-1.9.1.min.js.
        /// </summary>
        internal static string JQUERY_FILE_URL {
            get {
                return ResourceManager.GetString("JQUERY_FILE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yquery.
        /// </summary>
        internal static string JQUERY_KEY {
            get {
                return ResourceManager.GetString("JQUERY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:&apos;{1}&apos;,.
        /// </summary>
        internal static string JS_ARGUMENT_STRING_FORMAT {
            get {
                return ResourceManager.GetString("JS_ARGUMENT_STRING_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;region&quot;&gt;&lt;div id=&quot;{0}&quot;&gt;&lt;/div&gt;&lt;div id=&quot;{1}&quot;&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        internal static string RENDER_AVATAR_CONTENT {
            get {
                return ResourceManager.GetString("RENDER_AVATAR_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dialog&quot;&gt;&lt;/div&gt;.
        /// </summary>
        internal static string RENDER_PANEL_CONTENT {
            get {
                return ResourceManager.GetString("RENDER_PANEL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ypi.df.createAvatar({.
        /// </summary>
        internal static string SCRIPT_GENERATOR_CREATE_AVATAR {
            get {
                return ResourceManager.GetString("SCRIPT_GENERATOR_CREATE_AVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to });.
        /// </summary>
        internal static string SCRIPT_GENERATOR_CREATE_AVATAR_END {
            get {
                return ResourceManager.GetString("SCRIPT_GENERATOR_CREATE_AVATAR_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ypi.df.init({.
        /// </summary>
        internal static string SCRIPT_GENERATOR_INIT {
            get {
                return ResourceManager.GetString("SCRIPT_GENERATOR_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onload:function(options){.
        /// </summary>
        internal static string SCRIPT_GENERATOR_LOAD {
            get {
                return ResourceManager.GetString("SCRIPT_GENERATOR_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }}).
        /// </summary>
        internal static string SCRIPT_GENERATOR_LOAD_END {
            get {
                return ResourceManager.GetString("SCRIPT_GENERATOR_LOAD_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; src=&quot;{0}&quot;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string SCRIPT_INCLUDE {
            get {
                return ResourceManager.GetString("SCRIPT_INCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;{0}&lt;/script&gt;.
        /// </summary>
        internal static string SCRIPT_YPI_BASE {
            get {
                return ResourceManager.GetString("SCRIPT_YPI_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;$(document).ready(function () {           
        ///		ypi.df.invokeInit(); 	
        ///	});&lt;/script&gt;.
        /// </summary>
        internal static string SCRIPT_YPI_START {
            get {
                return ResourceManager.GetString("SCRIPT_YPI_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}:Avatar runat=server&gt;&lt;/{0}:Avatar&gt;.
        /// </summary>
        internal static string TOOLBOX_DATA_AVATAR {
            get {
                return ResourceManager.GetString("TOOLBOX_DATA_AVATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ypi_base.
        /// </summary>
        internal static string YPI_BASE_KEY {
            get {
                return ResourceManager.GetString("YPI_BASE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YpiControl.dialog.css.
        /// </summary>
        internal static string YPI_CSS_FILE_URL {
            get {
                return ResourceManager.GetString("YPI_CSS_FILE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string YPI_MIN_CUSTOM_KEY {
            get {
                return ResourceManager.GetString("YPI_MIN_CUSTOM_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YpiControl.custom.js.
        /// </summary>
        internal static string YPI_MIN_CUSTOM_URL {
            get {
                return ResourceManager.GetString("YPI_MIN_CUSTOM_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YpiControl.ypi_min-1.5.5.js.
        /// </summary>
        internal static string YPI_MIN_FILE_URL {
            get {
                return ResourceManager.GetString("YPI_MIN_FILE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ypi_min.
        /// </summary>
        internal static string YPI_MIN_KEY {
            get {
                return ResourceManager.GetString("YPI_MIN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ypi_start.
        /// </summary>
        internal static string YPI_START_KEY {
            get {
                return ResourceManager.GetString("YPI_START_KEY", resourceCulture);
            }
        }
    }
}
